version: "3.7"

services:
  app:
    build: .
    image: tinify_img
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    container_name: "tinify_ctn"
    entrypoint: ["sh"]
    # entrypoint: ["sh", "-c", "sleep 2073600"]